import { useNavigate } from 'react-router-dom';

export default function TermsPage() {
  const navigate = useNavigate();

  return (
    <div style={{ padding: '32px', maxWidth: '800px', margin: '0 auto', width: '100%', color: 'var(--text-primary)' }}>
      <button 
        onClick={() => navigate(-1)}
        style={{ background: 'transparent', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '8px' }}
      >
        <ion-icon name="arrow-back-outline"></ion-icon> Back
      </button>
      
      <h1 style={{ fontSize: '32px', marginBottom: '24px' }}>Terms of Service</h1>
      
      <div style={{ lineHeight: '1.6', color: 'var(--text-secondary)' }}>
        <p style={{ marginBottom: '16px' }}><strong>Last Updated: June 15, 2026</strong></p>
        <p style={{ marginBottom: '16px' }}>
          Welcome to Graham AI ("Graham," "we," "us," or "our"). These Terms of Service ("Terms") govern your access to and use of the Graham AI mobile application and related services (collectively, the "Service"). Please read these Terms carefully before using the Service. By accessing or using the Service, you agree to be bound by these Terms.
        </p>

        {/* 1. Acceptance of Terms */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>1. Acceptance of Terms</h2>
        <p style={{ marginBottom: '16px' }}>
          By creating an account or using the Service, you confirm that you are at least 13 years of age and agree to comply with and be bound by these Terms. If you do not agree with any part of these Terms, you must not use the Service.
        </p>

        {/* 2. AI-Generated Content */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>2. AI-Generated Content</h2>
        <p style={{ marginBottom: '12px' }}>
          Graham uses artificial intelligence to provide stock analysis, investment insights, and financial information. You acknowledge and agree that:
        </p>
        <ul style={{ marginBottom: '16px', paddingLeft: '24px' }}>
          <li style={{ marginBottom: '8px' }}><strong>Not Financial Advice:</strong> All content generated by Graham's AI — including Advisor chat responses, stock scans, Deep Dive reports, and any other analysis — is for <strong>educational and informational purposes only</strong> and does not constitute professional financial advice, investment advice, tax advice, or legal advice.</li>
          <li style={{ marginBottom: '8px' }}><strong>No Guarantees:</strong> AI-generated content may contain errors, inaccuracies, or outdated information. Graham does not guarantee the accuracy, completeness, or reliability of any AI-generated content.</li>
          <li style={{ marginBottom: '8px' }}><strong>Your Responsibility:</strong> You are solely responsible for any investment decisions you make. Always conduct your own research and consider consulting a qualified financial professional before making investment decisions.</li>
          <li style={{ marginBottom: '8px' }}><strong>Not a Fiduciary:</strong> Graham is not a registered investment advisor, broker-dealer, or financial planner. No fiduciary relationship is created between you and Graham by your use of the Service.</li>
        </ul>

        {/* 3. Third-Party Services */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>3. Third-Party Services</h2>
        <p style={{ marginBottom: '12px' }}>
          Graham integrates with the following third-party services to deliver its features:
        </p>
        <ul style={{ marginBottom: '16px', paddingLeft: '24px' }}>
          <li style={{ marginBottom: '8px' }}><strong>Google Gemini AI:</strong> Graham uses Google's Gemini AI service to process your queries, analyze financial data, and generate investment insights. Your use of AI features is also subject to Google's Terms of Service and Privacy Policy.</li>
          <li style={{ marginBottom: '8px' }}><strong>Apple Intelligence:</strong> On supported Apple devices, Graham may leverage Apple Intelligence for on-device AI processing. Such processing is governed by Apple's terms and privacy practices.</li>
          <li style={{ marginBottom: '8px' }}><strong>Google Firebase:</strong> We use Google Firebase for authentication, data storage, and app infrastructure.</li>
          <li style={{ marginBottom: '8px' }}><strong>Apple App Store & Stripe:</strong> Subscription payments are processed through Apple (for in-app purchases) and Stripe (for web-based payments), each subject to their own terms and policies.</li>
        </ul>
        <p style={{ marginBottom: '16px' }}>
          We are not responsible for the practices or policies of any third-party services. We encourage you to review the terms and privacy policies of these third-party providers.
        </p>

        {/* 4. Data Sharing with AI */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>4. Data Sharing with AI</h2>
        <p style={{ marginBottom: '12px' }}>
          By using Graham's AI-powered features, you acknowledge and consent to the following:
        </p>
        <ul style={{ marginBottom: '16px', paddingLeft: '24px' }}>
          <li style={{ marginBottom: '8px' }}>Your queries, uploaded images (such as screenshots and portfolio photos), and conversation history may be transmitted to Google's Gemini API for processing.</li>
          <li style={{ marginBottom: '8px' }}>This data transmission is necessary for Graham to provide AI-generated analysis and responses.</li>
          <li style={{ marginBottom: '8px' }}>Graham does not sell your personal data to any third party.</li>
        </ul>
        <p style={{ marginBottom: '16px' }}>
          For complete details on how your data is collected, used, and protected, please refer to our <strong>Privacy Policy</strong>.
        </p>

        {/* 5. Subscriptions and Payments */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>5. Subscriptions and Payments</h2>
        <p style={{ marginBottom: '12px' }}>
          Certain features of Graham require a paid subscription. By subscribing, you agree to the following:
        </p>
        <ul style={{ marginBottom: '16px', paddingLeft: '24px' }}>
          <li style={{ marginBottom: '8px' }}>Subscription fees are billed on a recurring basis (monthly or annually) depending on the plan you choose.</li>
          <li style={{ marginBottom: '8px' }}>You may cancel your subscription at any time. Cancellation will take effect at the end of your current billing period.</li>
          <li style={{ marginBottom: '8px' }}>Refunds for in-app purchases are subject to Apple's refund policies. Refunds for web subscriptions are subject to our refund policy and Stripe's terms.</li>
          <li style={{ marginBottom: '8px' }}>We reserve the right to change subscription pricing with reasonable notice to existing subscribers.</li>
        </ul>

        {/* 6. User Conduct */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>6. User Conduct</h2>
        <p style={{ marginBottom: '12px' }}>You agree not to:</p>
        <ul style={{ marginBottom: '16px', paddingLeft: '24px' }}>
          <li style={{ marginBottom: '8px' }}>Use the Service for any unlawful purpose or in violation of any applicable laws or regulations</li>
          <li style={{ marginBottom: '8px' }}>Attempt to reverse engineer, decompile, or disassemble any part of the Service</li>
          <li style={{ marginBottom: '8px' }}>Interfere with or disrupt the Service or servers connected to the Service</li>
          <li style={{ marginBottom: '8px' }}>Use automated means (bots, scrapers, etc.) to access the Service without our express written permission</li>
          <li style={{ marginBottom: '8px' }}>Resell, redistribute, or sublicense any part of the Service or its AI-generated content</li>
        </ul>

        {/* 7. Intellectual Property */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>7. Intellectual Property</h2>
        <p style={{ marginBottom: '16px' }}>
          The Service, including its design, features, code, and branding, is the property of Graham AI and is protected by intellectual property laws. You are granted a limited, non-exclusive, non-transferable license to use the Service for personal, non-commercial purposes in accordance with these Terms.
        </p>

        {/* 8. Disclaimer of Warranties */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>8. Disclaimer of Warranties</h2>
        <p style={{ marginBottom: '16px' }}>
          THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DISCLAIM ALL WARRANTIES, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT ANY DEFECTS WILL BE CORRECTED.
        </p>

        {/* 9. Limitation of Liability */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>9. Limitation of Liability</h2>
        <p style={{ marginBottom: '16px' }}>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, GRAHAM AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR REVENUE, WHETHER INCURRED DIRECTLY OR INDIRECTLY, ARISING FROM YOUR USE OF THE SERVICE OR ANY AI-GENERATED CONTENT. IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
        </p>

        {/* 10. Changes to Terms */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>10. Changes to Terms</h2>
        <p style={{ marginBottom: '16px' }}>
          We reserve the right to modify these Terms at any time. If we make material changes, we will notify you by updating the "Last Updated" date and, where appropriate, providing additional notice within the app or via email. Your continued use of the Service after changes are posted constitutes your acceptance of the revised Terms.
        </p>

        {/* 11. Contact Us */}
        <h2 style={{ fontSize: '20px', color: 'var(--text-primary)', marginTop: '32px', marginBottom: '12px' }}>11. Contact Us</h2>
        <p style={{ marginBottom: '16px' }}>
          If you have any questions about these Terms of Service, please contact us at:
        </p>
        <p style={{ marginBottom: '32px' }}>
          <strong>Email:</strong> support@grahamai.com
        </p>
      </div>
    </div>
  );
}
