// Context Finance — Mock AI Context Data
// In production, this would be generated by GPT-4/Claude from real-time news + price feeds

export const STOCK_CONTEXTS = {
  AAPL: {
    name: 'Apple Inc.',
    ticker: 'AAPL',
    change: -4.2,
    price: 189.43,
    happened: `A major microchip shipping container faced a temporary customs delay in Taiwan. It impacts the short-term supply logistics of the whole tech sector, not Apple's actual business value. Their fundamentals—$90B+ in quarterly revenue—remain completely untouched.`,
    bears: `"This might delay iPhone 18 shipments by 2 weeks. Supply chain fragility is a recurring problem, and margins could tighten if it persists."`,
    bulls: `"This is a minor supply blip. Consumer demand for the device is still tracking at an all-time high. It's a discount buying window for long-term holders."`,
    think: `Your money is totally safe. Historically, tech stocks completely recover from these types of logistics bottlenecks within 7 to 10 days. Apple has weathered far worse—this is noise, not signal.`,
    action: `Do nothing. Step away from your brokerage app. Apple isn't going anywhere. Check back in a week.`,
    sparkData: [78,72,75,71,68,65,70,66,62,58,55,52]
  },
  TSLA: {
    name: 'Tesla, Inc.',
    ticker: 'TSLA',
    change: -6.8,
    price: 241.17,
    happened: `Elon Musk made a controversial statement on social media about a political topic unrelated to Tesla's business. The media amplified it, and algorithmic traders triggered a sell-off. None of Tesla's production numbers, delivery forecasts, or technology roadmap changed.`,
    bears: `"CEO risk is real. Musk's unpredictability creates stock volatility and could alienate customers in key markets like Europe."`,
    bulls: `"This happens every few months and recovers every time. Tesla's energy storage division just reported record installations. The business is stronger than ever."`,
    think: `This is a textbook 'headline panic.' Tesla's actual car deliveries are up 22% year-over-year. The stock reacts to Musk's tweets; the business doesn't. These dips have recovered within 5–14 days, 9 out of the last 10 times.`,
    action: `Ignore the headlines. If you believe in electric vehicles and energy storage long-term, this changes nothing about your investment thesis.`,
    sparkData: [90,88,85,82,78,75,70,68,65,60,55,50]
  },
  NVDA: {
    name: 'NVIDIA Corporation',
    ticker: 'NVDA',
    change: 3.7,
    price: 924.56,
    happened: `A major cloud provider just announced a $12 billion expansion of their AI data centers, explicitly naming NVIDIA's H200 chips as the backbone. This confirms sustained demand for AI infrastructure through at least 2027.`,
    bears: `"NVIDIA is priced for perfection. Any slowdown in AI spending—even a quarter—could trigger a 20%+ correction. The valuation assumes flawless execution."`,
    bulls: `"We're still in the first inning of the AI infrastructure buildout. NVIDIA has 85%+ market share in AI chips with no credible competitor for 18+ months. This is a generational company."`,
    think: `NVIDIA is riding a genuine technology revolution, not hype. However, the stock price already reflects enormous growth expectations. If you own it, today's news validates your position. If you're considering buying, know that you're paying a premium for a premium company.`,
    action: `If you own NVIDIA, enjoy the green day. If you don't, do your research before chasing a rally. Never buy on FOMO.`,
    sparkData: [55,58,60,63,67,70,72,76,80,84,88,92]
  },
  MSFT: {
    name: 'Microsoft Corporation',
    ticker: 'MSFT',
    change: -1.8,
    price: 415.22,
    happened: `The EU announced a preliminary antitrust investigation into Microsoft's bundling of AI features with Office 365. This is a regulatory process that will take 12–24 months to resolve. No fines have been issued, and no product changes are required yet.`,
    bears: `"EU antitrust has teeth. Remember the $2.3B Google Shopping fine? Microsoft could face forced unbundling of Copilot from Office, hurting their AI monetization strategy."`,
    bulls: `"Microsoft has navigated EU regulation for 25 years. These investigations rarely result in material business changes. Meanwhile, Azure cloud revenue grew 29% last quarter."`,
    think: `Regulatory headlines sound scary but move slowly. Microsoft's last major EU antitrust case took 4 years and resulted in a fine that represented 0.5% of annual revenue. The company's diversified revenue streams make it remarkably resilient.`,
    action: `This is background noise. Microsoft is one of the most diversified tech companies on Earth. A preliminary EU investigation is not a reason to sell.`,
    sparkData: [75,74,73,72,70,69,68,67,66,65,64,63]
  },
  AMZN: {
    name: 'Amazon.com, Inc.',
    ticker: 'AMZN',
    change: 2.1,
    price: 192.88,
    happened: `Amazon Web Services (AWS) reported that enterprise AI workloads on their platform tripled in the last quarter. Additionally, Prime membership renewals hit 97%—the highest retention rate in company history.`,
    bears: `"Amazon's retail margins are still razor-thin. AWS growth is decelerating from 35% to 29%. Google Cloud and Azure are closing the gap faster than expected."`,
    bulls: `"97% Prime retention is a moat no competitor can touch. AWS is still the #1 cloud platform with 31% market share, and AI workloads are pure high-margin revenue."`,
    think: `Amazon is a slow-and-steady compounder. It won't give you the adrenaline of a meme stock, but it also won't give you the heart attack. The combination of sticky consumers (Prime) and enterprise infrastructure (AWS) creates a remarkably stable business.`,
    action: `Smile at the green. Amazon rewards patient investors. If you own it, you're on a proven long-term train.`,
    sparkData: [60,62,63,65,66,68,69,71,72,73,75,76]
  },
  META: {
    name: 'Meta Platforms, Inc.',
    ticker: 'META',
    change: -3.1,
    price: 478.55,
    happened: `Meta announced they're increasing AI infrastructure spending by $5 billion this year, higher than analysts expected. Wall Street is reacting to the higher costs, not the strategy. Revenue from Reels ads actually beat expectations by 12%.`,
    bears: `"Zuckerberg is spending aggressively again—remember the metaverse? $5B extra capex with no guaranteed return is exactly the kind of spending that burned investors in 2022."`,
    bulls: `"This is the opposite of 2022. Meta is spending on AI that directly improves ad targeting—their core cash cow. Reels revenue beat by 12%. The ROI on this spending is already visible."`,
    think: `Meta burned investors with metaverse spending, so Wall Street is trigger-shy about any capex increase. But context matters: this spending is on AI for ad optimization, which directly generates revenue. It's an investment in their profit engine, not a speculative side project.`,
    action: `Don't let 2022 PTSD cloud your judgment. Read the actual earnings call transcript—the spending has clear ROI justification. Hold steady.`,
    sparkData: [80,78,76,74,72,70,68,66,65,63,61,60]
  }
};

// OCR simulation: maps keywords from "screenshots" to tickers
export const OCR_KEYWORD_MAP = {
  'apple': 'AAPL', 'aapl': 'AAPL', 'iphone': 'AAPL',
  'tesla': 'TSLA', 'tsla': 'TSLA', 'elon': 'TSLA',
  'nvidia': 'NVDA', 'nvda': 'NVDA', 'gpu': 'NVDA',
  'microsoft': 'MSFT', 'msft': 'MSFT', 'windows': 'MSFT', 'azure': 'MSFT',
  'amazon': 'AMZN', 'amzn': 'AMZN', 'aws': 'AMZN', 'prime': 'AMZN',
  'meta': 'META', 'facebook': 'META', 'instagram': 'META', 'zuckerberg': 'META',
};

export const LOADING_MESSAGES = [
  'Scanning your screenshot...',
  'Identifying stock tickers...',
  'Pulling real-time market data...',
  'Analyzing price movement context...',
  'Generating your plain-English breakdown...',
  'Almost ready...'
];
